#!/usr/bin/env bash
# Builds the Linux AppImage and installs it as ~/Applications/dpcode/, then
# drops dpcode / dpcode-mcp-{start,stop,log} wrapper scripts into
# ~/.local/bin so you don't need zshrc aliases. The previous install is
# moved to ~/Applications/dpcode.bak (any earlier backup is removed first).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_DIR="${HOME}/Applications/dpcode"
BACKUP_DIR="${INSTALL_DIR}.bak"
BIN_DIR="${HOME}/.local/bin"
MCP_LOG="${HOME}/.dpcode/userdata/logs/mcp.log"
EXTRACT_DIR="$(mktemp -d -t dpcode-extract.XXXXXX)"
trap 'rm -rf "${EXTRACT_DIR}"' EXIT

cd "${REPO_ROOT}"

echo "==> Building Linux AppImage"
bun run dist:desktop:linux

APPIMAGE="$(ls -1t "${REPO_ROOT}"/release/*.AppImage | head -1)"
if [[ -z "${APPIMAGE}" || ! -f "${APPIMAGE}" ]]; then
  echo "No AppImage produced in ${REPO_ROOT}/release/" >&2
  exit 1
fi
echo "==> Built: ${APPIMAGE}"

chmod +x "${APPIMAGE}"

echo "==> Extracting AppImage"
( cd "${EXTRACT_DIR}" && "${APPIMAGE}" --appimage-extract >/dev/null )

if [[ ! -x "${EXTRACT_DIR}/squashfs-root/AppRun" ]]; then
  echo "Extraction did not produce squashfs-root/AppRun" >&2
  exit 1
fi

mkdir -p "$(dirname "${INSTALL_DIR}")"

if [[ -d "${BACKUP_DIR}" ]]; then
  echo "==> Removing previous backup ${BACKUP_DIR}"
  rm -rf "${BACKUP_DIR}"
fi

if [[ -d "${INSTALL_DIR}" ]]; then
  echo "==> Backing up current install -> ${BACKUP_DIR}"
  mv "${INSTALL_DIR}" "${BACKUP_DIR}"
fi

echo "==> Installing to ${INSTALL_DIR}"
mv "${EXTRACT_DIR}/squashfs-root" "${INSTALL_DIR}"

echo "==> Writing launcher wrappers to ${BIN_DIR}"
mkdir -p "${BIN_DIR}" "$(dirname "${MCP_LOG}")"

# Bake the install dir, repo path, and log path into the wrappers so they
# work from any cwd without needing zshrc aliases. DPCODE_MCP_BIND can be
# set in the user's environment to override the Tailscale-or-localhost
# default at start time.
cat > "${BIN_DIR}/dpcode" <<EOF
#!/usr/bin/env bash
# Launch the DP Code desktop app detached from the shell, then start the
# MCP server alongside it. Generated by scripts/install-local.sh.
set -euo pipefail
setsid -f "${INSTALL_DIR}/AppRun" </dev/null >/dev/null 2>&1
exec "${BIN_DIR}/dpcode-mcp-start"
EOF

cat > "${BIN_DIR}/dpcode-mcp-start" <<EOF
#!/usr/bin/env bash
# Start dpcode-mcp detached, binding to \$DPCODE_MCP_BIND if set, else the
# Tailscale IPv4 address on port 7331, else localhost:7331. Generated by
# scripts/install-local.sh.
set -euo pipefail
bind="\${DPCODE_MCP_BIND:-}"
if [[ -z "\${bind}" ]] && command -v tailscale >/dev/null 2>&1; then
  ts_ip="\$(tailscale ip -4 2>/dev/null | head -n1 || true)"
  if [[ -n "\${ts_ip}" ]]; then
    bind="\${ts_ip}:7331"
  fi
fi
bind="\${bind:-127.0.0.1:7331}"
mkdir -p "\$(dirname "${MCP_LOG}")"
DPCODE_MCP_BIND="\${bind}" setsid -f bun run --cwd "${REPO_ROOT}/apps/mcp" start \\
  </dev/null >>"${MCP_LOG}" 2>&1
echo "dpcode-mcp listening on \${bind} (log: ${MCP_LOG})"
EOF

cat > "${BIN_DIR}/dpcode-mcp-stop" <<EOF
#!/usr/bin/env bash
# Stop the dpcode-mcp server started by dpcode-mcp-start. Generated by
# scripts/install-local.sh.
set -euo pipefail
fuser -k 7331/tcp 2>/dev/null || true
pkill -f "dpcode/apps/mcp" 2>/dev/null || true
sleep 0.2
if pgrep -f "dpcode/apps/mcp" >/dev/null; then
  echo "dpcode-mcp still running"
  exit 1
fi
echo "dpcode-mcp stopped"
EOF

cat > "${BIN_DIR}/dpcode-mcp-log" <<EOF
#!/usr/bin/env bash
# Tail the dpcode-mcp log. Generated by scripts/install-local.sh.
exec tail -f "${MCP_LOG}"
EOF

chmod +x "${BIN_DIR}/dpcode" "${BIN_DIR}/dpcode-mcp-start" \
  "${BIN_DIR}/dpcode-mcp-stop" "${BIN_DIR}/dpcode-mcp-log"

echo "==> Done."
echo "    Launch with:    dpcode"
echo "    Stop MCP with:  dpcode-mcp-stop"
echo "    Tail MCP log:   dpcode-mcp-log"
if ! printf '%s' "${PATH}" | tr ':' '\n' | grep -Fxq "${BIN_DIR}"; then
  echo
  echo "    NOTE: ${BIN_DIR} is not on your PATH. Add it to your shell rc, e.g.:"
  echo "      export PATH=\"${BIN_DIR}:\$PATH\""
fi
echo "    To roll back:   rm -rf '${INSTALL_DIR}' && mv '${BACKUP_DIR}' '${INSTALL_DIR}'"
