#!/usr/bin/env bash
# Builds the Linux AppImage and installs it as ~/Applications/hscode/, then
# drops hscode / hscode-mcp-{start,stop,log} wrapper scripts into
# ~/.local/bin so you don't need zshrc aliases. The previous install is
# moved to ~/Applications/hscode.bak (any earlier backup is removed first).
#
# Migration: if a pre-rename ~/.dpcode home exists and ~/.hscode does not,
# the directory is renamed wholesale to ~/.hscode so saved sessions, MCP
# subscriptions, terminal history, and the sqlite state all carry across.
# Older wrappers in ~/.local/bin/dpcode* are cleaned up.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_DIR="${HOME}/Applications/hscode"
BACKUP_DIR="${INSTALL_DIR}.bak"
LEGACY_INSTALL_DIR="${HOME}/Applications/dpcode"
BIN_DIR="${HOME}/.local/bin"
HOME_DIR="${HOME}/.hscode"
LEGACY_HOME_DIR="${HOME}/.dpcode"
MCP_LOG="${HOME_DIR}/userdata/logs/mcp.log"
EXTRACT_DIR="$(mktemp -d -t hscode-extract.XXXXXX)"
trap 'rm -rf "${EXTRACT_DIR}"' EXIT

cd "${REPO_ROOT}"

if [[ -d "${LEGACY_HOME_DIR}" && ! -d "${HOME_DIR}" ]]; then
  echo "==> Migrating ${LEGACY_HOME_DIR} -> ${HOME_DIR}"
  mv "${LEGACY_HOME_DIR}" "${HOME_DIR}"
fi

echo "==> Building Linux AppImage"
bun run dist:desktop:linux

APPIMAGE="$(ls -1t "${REPO_ROOT}"/release/*.AppImage | head -1)"
if [[ -z "${APPIMAGE}" || ! -f "${APPIMAGE}" ]]; then
  echo "No AppImage produced in ${REPO_ROOT}/release/" >&2
  exit 1
fi
echo "==> Built: ${APPIMAGE}"

chmod +x "${APPIMAGE}"

echo "==> Extracting AppImage"
( cd "${EXTRACT_DIR}" && "${APPIMAGE}" --appimage-extract >/dev/null )

if [[ ! -x "${EXTRACT_DIR}/squashfs-root/AppRun" ]]; then
  echo "Extraction did not produce squashfs-root/AppRun" >&2
  exit 1
fi

mkdir -p "$(dirname "${INSTALL_DIR}")"

if [[ -d "${BACKUP_DIR}" ]]; then
  echo "==> Removing previous backup ${BACKUP_DIR}"
  rm -rf "${BACKUP_DIR}"
fi

if [[ -d "${INSTALL_DIR}" ]]; then
  echo "==> Backing up current install -> ${BACKUP_DIR}"
  mv "${INSTALL_DIR}" "${BACKUP_DIR}"
fi

echo "==> Installing to ${INSTALL_DIR}"
mv "${EXTRACT_DIR}/squashfs-root" "${INSTALL_DIR}"

if [[ -d "${LEGACY_INSTALL_DIR}" ]]; then
  echo "==> Legacy install at ${LEGACY_INSTALL_DIR} is no longer used; remove it when ready."
fi

echo "==> Writing launcher wrappers to ${BIN_DIR}"
mkdir -p "${BIN_DIR}" "$(dirname "${MCP_LOG}")"

# Clean up pre-rename wrappers so they don't shadow the new ones.
rm -f "${BIN_DIR}/dpcode" "${BIN_DIR}/dpcode-mcp-start" \
  "${BIN_DIR}/dpcode-mcp-stop" "${BIN_DIR}/dpcode-mcp-log"

# Bake the install dir, repo path, and log path into the wrappers so they
# work from any cwd without needing zshrc aliases. DPCODE_MCP_BIND can be
# set in the user's environment to override the Tailscale-or-localhost
# default at start time. (DPCODE_* env var names are preserved across the
# rename to keep existing dotfiles and remote tooling working.)
cat > "${BIN_DIR}/hscode" <<EOF
#!/usr/bin/env bash
# Launch the HS Code desktop app detached from the shell, then start the
# MCP server alongside it. Generated by scripts/install-local.sh.
set -euo pipefail
setsid -f "${INSTALL_DIR}/AppRun" </dev/null >/dev/null 2>&1
exec "${BIN_DIR}/hscode-mcp-start"
EOF

cat > "${BIN_DIR}/hscode-mcp-start" <<EOF
#!/usr/bin/env bash
# Start hscode's MCP server (dpcode-mcp package) detached, binding to
# \$DPCODE_MCP_BIND if set, else the Tailscale IPv4 address on port 7331,
# else localhost:7331. Generated by scripts/install-local.sh.
set -euo pipefail
bind="\${DPCODE_MCP_BIND:-}"
if [[ -z "\${bind}" ]] && command -v tailscale >/dev/null 2>&1; then
  ts_ip="\$(tailscale ip -4 2>/dev/null | head -n1 || true)"
  if [[ -n "\${ts_ip}" ]]; then
    bind="\${ts_ip}:7331"
  fi
fi
bind="\${bind:-127.0.0.1:7331}"
mkdir -p "\$(dirname "${MCP_LOG}")"
DPCODE_MCP_BIND="\${bind}" setsid -f bun run --cwd "${REPO_ROOT}/apps/mcp" start \\
  </dev/null >>"${MCP_LOG}" 2>&1
echo "hscode-mcp listening on \${bind} (log: ${MCP_LOG})"
EOF

cat > "${BIN_DIR}/hscode-mcp-stop" <<EOF
#!/usr/bin/env bash
# Stop the MCP server started by hscode-mcp-start. Matches both the new
# repo path and the legacy one so a pre-rename process can be killed too.
# Generated by scripts/install-local.sh.
set -euo pipefail
fuser -k 7331/tcp 2>/dev/null || true
pkill -f "${REPO_ROOT}/apps/mcp" 2>/dev/null || true
pkill -f "dpcode/apps/mcp" 2>/dev/null || true
sleep 0.2
if pgrep -f "${REPO_ROOT}/apps/mcp" >/dev/null || pgrep -f "dpcode/apps/mcp" >/dev/null; then
  echo "hscode-mcp still running"
  exit 1
fi
echo "hscode-mcp stopped"
EOF

cat > "${BIN_DIR}/hscode-mcp-log" <<EOF
#!/usr/bin/env bash
# Tail the hscode-mcp log. Generated by scripts/install-local.sh.
exec tail -f "${MCP_LOG}"
EOF

chmod +x "${BIN_DIR}/hscode" "${BIN_DIR}/hscode-mcp-start" \
  "${BIN_DIR}/hscode-mcp-stop" "${BIN_DIR}/hscode-mcp-log"

echo "==> Done."
echo "    Launch with:    hscode"
echo "    Stop MCP with:  hscode-mcp-stop"
echo "    Tail MCP log:   hscode-mcp-log"
if ! printf '%s' "${PATH}" | tr ':' '\n' | grep -Fxq "${BIN_DIR}"; then
  echo
  echo "    NOTE: ${BIN_DIR} is not on your PATH. Add it to your shell rc, e.g.:"
  echo "      export PATH=\"${BIN_DIR}:\$PATH\""
fi
echo "    To roll back:   rm -rf '${INSTALL_DIR}' && mv '${BACKUP_DIR}' '${INSTALL_DIR}'"
